package com.example.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.data.database.AnalyticsRecord
import com.example.ui.theme.AmberWarning
import com.example.ui.theme.BluePrimary
import com.example.ui.theme.GreenPrimary
import com.example.ui.theme.TealAccent
import com.example.ui.viewmodel.SurakkhaViewModel

@OptIn(ExperimentalLayoutApi::class)
@Composable
fun AnalyticsDashboardScreen(
    viewModel: SurakkhaViewModel,
    analytics: AnalyticsRecord?,
    isBangla: Boolean,
    modifier: Modifier = Modifier
) {
    val stats = analytics ?: AnalyticsRecord()

    LazyColumn(
        modifier = modifier
            .fillMaxSize()
            .testTag("analytics_screen"),
        contentPadding = PaddingValues(16.dp),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        // Section 1: Intro Header
        item {
            Card(
                colors = CardDefaults.cardColors(
                    containerColor = AmberWarning.copy(alpha = 0.08F)
                ),
                shape = RoundedCornerShape(12.dp)
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Icon(
                            imageVector = Icons.Default.Analytics,
                            contentDescription = null,
                            tint = AmberWarning,
                            modifier = Modifier.size(24.dp)
                        )
                        Spacer(modifier = Modifier.width(8.dp))
                        Text(
                            text = if (isBangla) "সামাজিক প্রভাব ও ব্যবহারকারী ট্র্যাকার" else "Social Impact & Engagement Tracker",
                            style = MaterialTheme.typography.titleMedium,
                            fontWeight = FontWeight.Bold,
                            color = AmberWarning
                        )
                    }
                    Spacer(modifier = Modifier.height(4.dp))
                    Text(
                        text = if (isBangla)
                            "সরকারি 'উদ্ভাবনী প্রজেক্ট শোকেসিং' কর্মসূচীর ড্যাশবোর্ড। সুরক্ষা এআই প্ল্যাটফর্মের মাধ্যমে বাংলাদেশের কতজন মানুষের জীবন রক্ষা ও সেবা লাভ হচ্ছে তা রিয়েল-টাইমে দেখুন।"
                            else "Dedicated live tracking dashboard proposed for Govt SEDP showcasing. Trace the real-time social value generated by Surakkha AI.",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                        lineHeight = 16.sp
                    )
                }
            }
        }

        // Section 2: Quick Impact Metrics Grid
        item {
            Text(
                text = if (isBangla) " রিয়েল-টাইম ইমপ্যাক্ট মেট্রিক্স" else " Live Impact Metrics",
                style = MaterialTheme.typography.titleMedium,
                fontWeight = FontWeight.Bold,
                color = MaterialTheme.colorScheme.onBackground
            )
            Spacer(modifier = Modifier.height(10.dp))
            
            Column(verticalArrangement = Arrangement.spacedBy(10.dp)) {
                // Row 1
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(10.dp)
                ) {
                    MetricGridCard(
                        title = if (isBangla) "উদ্ধারকৃত নিখোঁজ" else "Cases Resolved",
                        value = "${stats.solvedMissingPersons}",
                        unit = if (isBangla) "জন" else "people",
                        icon = Icons.Default.CheckCircle,
                        color = GreenPrimary,
                        modifier = Modifier.weight(1F)
                    )
                    MetricGridCard(
                        title = if (isBangla) "সচল অনুসন্ধান" else "Active Searches",
                        value = "${stats.activeMissingSearches}",
                        unit = if (isBangla) "টি কেস" else "active",
                        icon = Icons.Default.Search,
                        color = MaterialTheme.colorScheme.error,
                        modifier = Modifier.weight(1F)
                    )
                }

                // Row 2
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(10.dp)
                ) {
                    MetricGridCard(
                        title = if (isBangla) "সরলীকৃত পরিপত্র" else "Simplified Docs",
                        value = "${stats.simplifiedDocumentsCount}",
                        unit = if (isBangla) "টি দলিল" else "saved",
                        icon = Icons.Default.AssignmentTurnedIn,
                        color = TealAccent,
                        modifier = Modifier.weight(1F)
                    )
                    MetricGridCard(
                        title = if (isBangla) "চেকলিস্ট সম্পন্ন" else "Safety Milestones",
                        value = "${stats.disasterChecklistsCompleted}",
                        unit = if (isBangla) "টি কাজ" else "actions",
                        icon = Icons.Default.BookmarkAdded,
                        color = BluePrimary,
                        modifier = Modifier.weight(1F)
                    )
                }

                // Row 3
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(10.dp)
                ) {
                    MetricGridCard(
                        title = if (isBangla) "এআই চ্যাট আলাপন" else "AI Chat Queries",
                        value = "${stats.chatInteractionsCount}",
                        unit = if (isBangla) "টি বার্তা" else "turns",
                        icon = Icons.Default.ModeComment,
                        color = GreenPrimary,
                        modifier = Modifier.weight(1F)
                    )
                    MetricGridCard(
                        title = if (isBangla) "নিবন্ধিত সেচ্ছাসেবক" else "Active Volunteers",
                        value = "${stats.communityVolunteersRegistered}",
                        unit = if (isBangla) "জন" else "users",
                        icon = Icons.Default.Group,
                        color = AmberWarning,
                        modifier = Modifier.weight(1F)
                    )
                }
            }
        }

        // Section 3: Join Volunteer Call to action
        item {
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
                elevation = CardDefaults.cardElevation(defaultElevation = 2.dp)
            ) {
                Column(
                    modifier = Modifier.padding(16.dp),
                    horizontalAlignment = Alignment.CenterHorizontally
                ) {
                    Text(
                        text = if (isBangla) " আপনিও কি একজন স্বেচ্ছাসেবক হতে চান?" else "Become a Surakkha AI Community Volunteer?",
                        style = MaterialTheme.typography.bodyMedium,
                        fontWeight = FontWeight.Bold,
                        textAlign = TextAlign.Center
                    )
                    Spacer(modifier = Modifier.height(6.dp))
                    Text(
                        text = if (isBangla) 
                            "আমাদের স্বেচ্ছাসেবক নেটওয়ার্কে যোগ দিয়ে নিখোঁজ ব্যক্তি সনাক্তকরণ ও দুর্যোগ মোকাবেলায় সরকারের সহযোগী হোন।"
                            else "Join our national database. Receive geolocated alerts for missing children or cyclones in your local village.",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                        textAlign = TextAlign.Center,
                        lineHeight = 16.sp,
                        modifier = Modifier.padding(horizontal = 12.dp)
                    )
                    Spacer(modifier = Modifier.height(12.dp))
                    Button(
                        onClick = { viewModel.registerNewVolunteer() },
                        colors = ButtonDefaults.buttonColors(containerColor = AmberWarning),
                        modifier = Modifier.fillMaxWidth().height(44.dp).testTag("register_volunteer_button")
                    ) {
                        Icon(imageVector = Icons.Default.VolunteerActivism, contentDescription = null)
                        Spacer(modifier = Modifier.width(8.dp))
                        Text(
                            text = if (isBangla) "স্বেচ্ছাসেবক হিসেবে নিবন্ধন করুন" else "Register as Active Volunteer",
                            fontWeight = FontWeight.Bold
                        )
                    }
                }
            }
        }

        // Section 4: Scalability & Technical Feasibility Details for SEDP Jury
        item {
            Card(
                colors = CardDefaults.cardColors(
                    containerColor = MaterialTheme.colorScheme.primaryContainer.copy(alpha = 0.2F)
                ),
                shape = RoundedCornerShape(12.dp)
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Text(
                        text = if (isBangla) "আইসিটি মন্ত্রণালয় পিআইপি সংযুক্তি (Jury Notes)" else "ICT Ministry API Integration Strategy (Jury Notes)",
                        fontWeight = FontWeight.Bold,
                        color = MaterialTheme.colorScheme.primary,
                        style = MaterialTheme.typography.bodyMedium
                    )
                    Spacer(modifier = Modifier.height(8.dp))
                    Text(
                        text = if (isBangla)
                            "১. বাংলাদেশ পুলিশ নিখোঁজ সার্ভার (Database integration ready)\n" +
                            "২. বাংলাদেশ আবহাওয়া অধিদপ্তর (BMD API live integration)\n" +
                            "৩. শিক্ষা বোর্ড ও ক্যাবিনেট সচিবালয় পরিপত্র ফিড\n" +
                            "৪. অফলাইন এআই মডিউল (low-end ডিভাইসের জন্য অপ্টিমাইজড)"
                            else "• Bangladesh National Police DB (Integration channels ready)\n" +
                            "• Bangladesh Meteorological Dept (BMD XML live parsing)\n" +
                            "• Education Boards circular databases (Crawling setup)\n" +
                            "• Offline local fallback models (Tuned for low-end rural nodes)",
                        style = MaterialTheme.typography.labelSmall,
                        lineHeight = 16.sp,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }
            }
        }

        item {
            Spacer(modifier = Modifier.height(24.dp))
        }
    }
}

@Composable
fun MetricGridCard(
    title: String,
    value: String,
    unit: String,
    icon: androidx.compose.ui.graphics.vector.ImageVector,
    color: Color,
    modifier: Modifier = Modifier
) {
    Card(
        modifier = modifier.height(115.dp),
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
        elevation = CardDefaults.cardElevation(defaultElevation = 1.dp)
    ) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(12.dp),
            verticalArrangement = Arrangement.SpaceBetween
        ) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Text(
                    text = title,
                    style = MaterialTheme.typography.labelSmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    fontWeight = FontWeight.Bold,
                    maxLines = 1,
                    overflow = TextOverflow.Ellipsis
                )
                Icon(
                    imageVector = icon,
                    contentDescription = null,
                    tint = color,
                    modifier = Modifier.size(16.dp)
                )
            }
            Column {
                Text(
                    text = value,
                    style = MaterialTheme.typography.headlineMedium,
                    fontWeight = FontWeight.ExtraBold,
                    color = MaterialTheme.colorScheme.onSurface
                )
                Text(
                    text = unit,
                    color = color,
                    style = MaterialTheme.typography.labelSmall,
                    fontWeight = FontWeight.Bold
                )
            }
        }
    }
}
